services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: rent_cars_db
      POSTGRES_USER: rent_cars
      POSTGRES_PASSWORD: rent_cars
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
